/**
 * Lista completa de códigos de discagem internacional (DDI).
 * Ordenada com países de língua portuguesa e mais comuns no topo.
 */
export const COUNTRY_CODES: { code: string; name: string }[] = [
  { code: "+55", name: "Brasil" },
  { code: "+351", name: "Portugal" },
  { code: "+1", name: "EUA / Canadá" },
  { code: "+54", name: "Argentina" },
  { code: "+34", name: "Espanha" },
  { code: "+44", name: "Reino Unido" },
  { code: "+49", name: "Alemanha" },
  { code: "+33", name: "França" },
  { code: "+39", name: "Itália" },
  { code: "+61", name: "Austrália" },
  { code: "+52", name: "México" },
  { code: "+57", name: "Colômbia" },
  { code: "+58", name: "Venezuela" },
  { code: "+56", name: "Chile" },
  { code: "+51", name: "Peru" },
  { code: "+593", name: "Equador" },
  { code: "+595", name: "Paraguai" },
  { code: "+598", name: "Uruguai" },
  { code: "+591", name: "Bolívia" },
  { code: "+31", name: "Holanda" },
  { code: "+41", name: "Suíça" },
  { code: "+43", name: "Áustria" },
  { code: "+86", name: "China" },
  { code: "+81", name: "Japão" },
  { code: "+91", name: "Índia" },
  { code: "+82", name: "Coreia do Sul" },
  { code: "+62", name: "Indonésia" },
  { code: "+60", name: "Malásia" },
  { code: "+63", name: "Filipinas" },
  { code: "+65", name: "Singapura" },
  { code: "+66", name: "Tailândia" },
  { code: "+64", name: "Nova Zelândia" },
  { code: "+7", name: "Rússia / Cazaquistão" },
  { code: "+380", name: "Ucrânia" },
  { code: "+48", name: "Polônia" },
  { code: "+46", name: "Suécia" },
  { code: "+47", name: "Noruega" },
  { code: "+45", name: "Dinamarca" },
  { code: "+358", name: "Finlândia" },
  { code: "+353", name: "Irlanda" },
  { code: "+32", name: "Bélgica" },
  { code: "+30", name: "Grécia" },
  { code: "+420", name: "República Tcheca" },
  { code: "+36", name: "Hungria" },
  { code: "+40", name: "Romênia" },
  { code: "+359", name: "Bulgária" },
  { code: "+381", name: "Sérvia" },
  { code: "+385", name: "Croácia" },
  { code: "+386", name: "Eslovênia" },
  { code: "+387", name: "Bósnia" },
  { code: "+383", name: "Kosovo" },
  { code: "+389", name: "Macedônia do Norte" },
  { code: "+382", name: "Montenegro" },
  { code: "+370", name: "Lituânia" },
  { code: "+371", name: "Letônia" },
  { code: "+372", name: "Estônia" },
  { code: "+373", name: "Moldávia" },
  { code: "+375", name: "Bielorrússia" },
  { code: "+90", name: "Turquia" },
  { code: "+972", name: "Israel" },
  { code: "+971", name: "Emirados Árabes" },
  { code: "+966", name: "Arábia Saudita" },
  { code: "+20", name: "Egito" },
  { code: "+27", name: "África do Sul" },
  { code: "+234", name: "Nigéria" },
  { code: "+254", name: "Quênia" },
  { code: "+233", name: "Gana" },
  { code: "+212", name: "Marrocos" },
  { code: "+213", name: "Argélia" },
  { code: "+216", name: "Tunísia" },
  { code: "+502", name: "Guatemala" },
  { code: "+503", name: "El Salvador" },
  { code: "+504", name: "Honduras" },
  { code: "+505", name: "Nicarágua" },
  { code: "+506", name: "Costa Rica" },
  { code: "+507", name: "Panamá" },
  { code: "+509", name: "Haiti" },
  { code: "+592", name: "Guiana" },
  { code: "+597", name: "Suriname" },
  { code: "+501", name: "Belize" },
  { code: "+53", name: "Cuba" },
  { code: "+1", name: "Rep. Dominicana / Porto Rico" },
  { code: "+670", name: "Timor-Leste" },
  { code: "+258", name: "Moçambique" },
  { code: "+244", name: "Angola" },
  { code: "+245", name: "Guiné-Bissau" },
  { code: "+238", name: "Cabo Verde" },
  { code: "+239", name: "São Tomé e Príncipe" },
  { code: "+240", name: "Guiné Equatorial" },
  { code: "+241", name: "Gabão" },
  { code: "+242", name: "Congo" },
  { code: "+243", name: "Congo (RDC)" },
  { code: "+250", name: "Ruanda" },
  { code: "+255", name: "Tanzânia" },
  { code: "+256", name: "Uganda" },
  { code: "+257", name: "Burundi" },
  { code: "+260", name: "Zâmbia" },
  { code: "+263", name: "Zimbábue" },
  { code: "+264", name: "Namíbia" },
  { code: "+267", name: "Botswana" },
  { code: "+268", name: "Eswatini" },
  { code: "+269", name: "Comores" },
  { code: "+261", name: "Madagascar" },
  { code: "+230", name: "Maurícia" },
  { code: "+248", name: "Seicheles" },
  { code: "+220", name: "Gâmbia" },
  { code: "+221", name: "Senegal" },
  { code: "+223", name: "Mali" },
  { code: "+224", name: "Guiné" },
  { code: "+225", name: "Costa do Marfim" },
  { code: "+226", name: "Burkina Faso" },
  { code: "+227", name: "Níger" },
  { code: "+228", name: "Togo" },
  { code: "+229", name: "Benim" },
  { code: "+231", name: "Libéria" },
  { code: "+232", name: "Serra Leoa" },
  { code: "+249", name: "Sudão" },
  { code: "+251", name: "Etiópia" },
  { code: "+252", name: "Somália" },
  { code: "+253", name: "Djibuti" },
  { code: "+291", name: "Eritreia" },
  { code: "+500", name: "Ilhas Falkland" },
  { code: "+672", name: "Antártica" },
  { code: "+350", name: "Gibraltar" },
  { code: "+352", name: "Luxemburgo" },
  { code: "+354", name: "Islândia" },
  { code: "+355", name: "Albânia" },
  { code: "+356", name: "Malta" },
  { code: "+357", name: "Chipre" },
  { code: "+374", name: "Armênia" },
  { code: "+376", name: "Andorra" },
  { code: "+377", name: "Mônaco" },
  { code: "+378", name: "San Marino" },
  { code: "+379", name: "Vaticano" },
  { code: "+423", name: "Liechtenstein" },
  { code: "+421", name: "Eslováquia" },
  { code: "+998", name: "Uzbequistão" },
  { code: "+992", name: "Tajiquistão" },
  { code: "+993", name: "Turcomenistão" },
  { code: "+994", name: "Azerbaijão" },
  { code: "+995", name: "Geórgia" },
  { code: "+996", name: "Quirguistão" },
  { code: "+977", name: "Nepal" },
  { code: "+880", name: "Bangladesh" },
  { code: "+94", name: "Sri Lanka" },
  { code: "+92", name: "Paquistão" },
  { code: "+98", name: "Irã" },
  { code: "+964", name: "Iraque" },
  { code: "+961", name: "Líbano" },
  { code: "+963", name: "Síria" },
  { code: "+970", name: "Palestina" },
  { code: "+973", name: "Bahrein" },
  { code: "+974", name: "Catar" },
  { code: "+965", name: "Kuwait" },
  { code: "+968", name: "Omã" },
  { code: "+962", name: "Jordânia" },
  { code: "+967", name: "Iêmen" },
  { code: "+960", name: "Maldivas" },
  { code: "+670", name: "Timor-Leste" },
  { code: "+673", name: "Brunei" },
  { code: "+855", name: "Camboja" },
  { code: "+856", name: "Laos" },
  { code: "+95", name: "Mianmar" },
  { code: "+84", name: "Vietnã" },
  { code: "+672", name: "Antártica/Oceania" },
  { code: "+674", name: "Nauru" },
  { code: "+675", name: "Papua-Nova Guiné" },
  { code: "+676", name: "Tonga" },
  { code: "+677", name: "Ilhas Salomão" },
  { code: "+678", name: "Vanuatu" },
  { code: "+679", name: "Fiji" },
  { code: "+685", name: "Samoa" },
  { code: "+686", name: "Kiribati" },
  { code: "+687", name: "Nova Caledônia" },
  { code: "+688", name: "Tuvalu" },
  { code: "+689", name: "Polinésia Francesa" },
  { code: "+690", name: "Toquelau" },
  { code: "+691", name: "Micronésia" },
  { code: "+692", name: "Ilhas Marshall" },
  { code: "+1-242", name: "Bahamas" },
  { code: "+1-246", name: "Barbados" },
  { code: "+1-268", name: "Antígua e Barbuda" },
  { code: "+1-284", name: "Ilhas Virgens Britânicas" },
  { code: "+1-345", name: "Ilhas Cayman" },
  { code: "+1-473", name: "Granada" },
  { code: "+1-649", name: "Turcas e Caicos" },
  { code: "+1-664", name: "Montserrat" },
  { code: "+1-721", name: "São Martinho" },
  { code: "+1-758", name: "Santa Lúcia" },
  { code: "+1-767", name: "Dominica" },
  { code: "+1-784", name: "São Vicente e Granadinas" },
  { code: "+1-868", name: "Trinidad e Tobago" },
  { code: "+1-869", name: "São Cristóvão e Névis" },
  { code: "+1-876", name: "Jamaica" },
  { code: "+297", name: "Aruba" },
  { code: "+298", name: "Ilhas Feroé" },
  { code: "+299", name: "Groenlândia" },
];

// Remove duplicates by code (keep first occurrence)
const seen = new Set<string>();
export const UNIQUE_COUNTRY_CODES = COUNTRY_CODES.filter(({ code }) => {
  if (seen.has(code)) return false;
  seen.add(code);
  return true;
});

export function parsePhoneForDisplay(
  phone: string,
  codes: { code: string }[] = UNIQUE_COUNTRY_CODES
): { countryCode: string; localNumber: string } {
  if (!phone?.trim()) return { countryCode: "+55", localNumber: "" };
  const trimmed = phone.trim();
  if (!trimmed.startsWith("+")) return { countryCode: "+55", localNumber: trimmed.replace(/\D/g, "") };
  const sorted = [...codes].sort((a, b) => b.code.length - a.code.length);
  for (const { code } of sorted) {
    if (trimmed.startsWith(code)) {
      return { countryCode: code, localNumber: trimmed.slice(code.length).replace(/\D/g, "") };
    }
  }
  return { countryCode: "+55", localNumber: trimmed.replace(/\D/g, "") };
}
