/**
 * Lista fixa de tipos de negócio disponíveis.
 * Ordenada alfabeticamente, exceto "Outro" que sempre fica no final.
 */
export const BUSINESS_TYPES = [
  "Accounting Services",
  "Administrative and Support Services",
  "Administrative Management and General Management Consulting Services",
  "All Other Support Activities for Transportation",
  "Artificial Intelligence Consulting services and SAAS products",
  "Audiovisual production",
  "Business consulting",
  "Business Consulting & Investment",
  "Business management and administrative support",
  "Business management, technology, and administrative services",
  "Computer system design services & Software publishers",
  "Consulting",
  "Consulting & Investments",
  "Consulting & Online Retail",
  "Custom Computer Programming Services",
  "Digital Marketing",
  "Digital Products",
  "Digital Products & Services",
  "Digital Sales",
  "Dropshipping",
  "ECommerce",
  "ECommerce & Consulting",
  "ECommerce & Digital Marketing",
  "Financial Services",
  "Flooring Services",
  "Freight Transportation Arrangement",
  "General Services and Sales",
  "Graphic Design Services",
  "Import and Export",
  "Influencers, Digital Marketing",
  "Internet Publishing and Broadcasting and Web Search Portals",
  "IT Consulting",
  "IT Managed Service Provider",
  "Logistics Consulting",
  "Marketing & Consulting",
  "Marketing & Software Development",
  "Marketing Call Center",
  "Marketing Consulting & Ecommerce",
  "Offices of other Holding companies",
  "Online Retail",
  "Online Services",
  "Other Management Consulting Services",
  "Performing Art Company",
  "Professional and management development training",
  "Real Estate",
  "Software Development",
  "Software Development & Financial Services",
  "Software Publishers",
  "Technology Services and Consulting",
  "Teleproduction and Other Postproduction Services",
  "Travel Agency - NAICS 561510",
  "Outro",
] as const;
